source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'Map_Tests', :exclusive => true do
  pod "IOS-Map", :path => "../"

  
end

target 'IOS-Map-Example', :exclusive => true do
  pod "IOS-Map", :path => "../"


end
